language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm
  - external_data
  - .drake

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
- Rscript analysis/data-fetch.R
- Rscript make.R

deploy:
  provider: script
  script: netlify deploy --prod --dir _book 
  skip_cleanup: true